# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "install yq"
          sudo snap install yq
          echo "install unzip"
          sudo apt-get install -y unzip zip          
          echo "install 3.10"
          sudo apt-get install -y python3.10-distutils
          sudo apt update
          sudo apt upgrade -y 
          echo "install deadsnake"          
          sudo add-apt-repository -y ppa:deadsnakes/ppa 
          sudo apt update
          echo "install 3.11"          
          sudo apt-get install -y python3.11 
          sudo apt-get install -y python3.11-distutils          
          sudo unlink /usr/bin/python3
          sudo ln -s /usr/bin/python3.10 /usr/bin/python3
          echo "install get-pip"          
          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
          curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3.10
          
          echo "verifing python versions:"
          
          python3 --version
          python3.11 --version
          
          git config --global user.email "jenkins@seebo.com"
          git config --global user.name "jenkins@seebo.com"
          
          cat > .pypirc <<EOF
          [distutils]
          Index-servers =
            SeeboDS
          
          [SeeboDS]
          Repository = https://seebo-iot.pkgs.visualstudio.com/c97e1367-bda5-4575-a58c-fddc3d09c569/_packaging/SeeboDS/pypi/upload
          username  = onzcnuzzalqv2kpem7kjsiupq6aozmkxl77mssaaryis3osyk4oa
          password = onzcnuzzalqv2kpem7kjsiupq6aozmkxl77mssaaryis3osyk4oa
      
